########################
#   SIR by CroaBeast   #
# Depressed since 2004 #
########################
# Want to use unicode characters? Check this site: https://coolsymbol.com

# If enabled, those files will be updated automatically.
# Don't worry, it doesn't delete any comments at all.
update:
  config: true
  lang: true

# Some useful options for this plugin if you want to change something.
options:
  # It will send the join/quit messages to the server's console.
  send-console: true
  # Every message in lang.yml that start with this string,
  # will have the main-prefix first.
  prefix-in-config: '<P>'
  # FOR lang.yml, messages.yml files AND FOR CHAT TYPE!!
  # Put this first on those chat messages you want to center.
  center-prefix: '<C>'
  # ONLY FOR messages.yml file AND FOR TITLE TYPE!!
  # If you want title AND subtitle, use it to split the message.
  line-separator: '<n>'

# If a login plugin is installed, this section will be activated.
# Compatible login plugins: [ AuthMe, UserLogin ]
# If you want support for another login plugin, you can
# suggest it in the Spigot resource page.
login:
  # it will send the messages after the player logs-in/register.
  # Disabling this, messages will send like no compatible login
  # plugin is installed in the server.
  send-after: true
  # This will send messages after some in-game ticks.
  # You can set this to 0 if you don't want this option or deleting
    # this path completely.
  ticks-after: 10
  # Enabling this will teleport the player before log-in/register.
  # Disabling it will teleport AFTER the player does it.
  spawn-before: true

# If a vanish plugin is installed, this section will be activated.
# Compatible vanish plugins: [ CMI, EssentialsX ]
# If you want support for another vanish plugin, you can
# suggest it in the Spigot resource page.
vanish:
  # It will send a join/quit message when a player changes its vanish
  # status. Disabling this won't send any messages when the vanish
  # status of a player changes.
  trigger: true
  # If a player is vanished and this option is enabled, won't send
  # any join/quit message to that player.
  silent: true
  # If a message has a "spawn:" section, and this option is disabled,
  # that spawn section won't be executed.
  do-spawn: false
