########################
#   SIR by CroaBeast   #
# Depressed since 2004 #
########################
# Want to use unicode characters? Check this site: https://coolsymbol.com

# The Updater Checker for new plugin updates and new file settings.
updater:
  # Check for new plugin updates.
  plugin:
    # Sends a reminder when the plugin is completely enabled.
    # Disabling won't send any reminder.
    on-start: true
    # Sends a reminder to OP's or players with 'sir.admin.update'
    # permission. Disabling won't send any reminder.
    send-op: true
  # If enabled, the selected files will be updated automatically.
  # Don't worry, it doesn't delete any default comments at all.
  # Available files: config, lang, modules, announces, join-quit,
  #                 motd, chat, emojis, discord, advances, filters
  files: [ config, lang, modules ]

# Some useful options for this plugin if you want to change them.
options:
  # It will log the join/quit messages, the announcements from
  # announces.yml, and the advancement messages from advances.yml
  # to the server's console.
  send-console: true
  # This option is ONLY for the /print command.
  # Enabling this will parse color and placeholders in the logger.
  log-format: false
  # If enabled, it will remove all unnecessary spaces for every
  # message to send. Recommended leaving this 'true'.
  hard-spacing: true
  # If enabled, it will check if the permission is set to that
  # player; then if true, it will check if the player has the perm
  # value set to true. Recommended leaving this 'false'.
  # If enabled, it will not check if a player is OP and ALSO for
  # wildcard-type permissions, like sir.* or worldedit.*.
  hard-perm-check: false
  # if enabled, it will show the prefix of the message type in
  # the console. Example:
  # [ACTION-BAR] My action bar message.
  show-prefix: true

# You can delete the values' section if you want to use the hard-coded values!
values:
  # Every message that start with this string, will have the main-prefix.
  lang-prefix-key: '<P>'
  # Valid only in SIR files or inputs that accept centered messages.
  # Put this first on those chat messages you want to center.
  center-prefix: '<C>'
  # Can be used in most of the plugin files and the /print command.
  # If you want to add more than one line in your CHAT type message,
  # or you want title AND subtitle, use it to split the message.
  line-separator: '<n>'