# If enabled, it will allow players to send blank messages using
# spaces ' '. Recommended leaving this 'false'.
allow-empty: false
# If enabled, it will send a unique specific format to the console,
# just to be it more simple. This option applies to ALL formats.
simple-logger:
  enabled: false
  # You can use PlaceholderAPI, {PREFIX} and {SUFFIX}
  format: ' &7{player}: {message}'
# If disabled, it won't use the default format (from AsyncPlayerChatEvent).
# This will also allow chat compatibility with these features:
# - InteractiveChat support
# - Ignore chat command
# - Per Radius channel
# - Hover and Click events
# Enabling this is NOT recommended.
default-format: false
# This section is for the default channel that applies to all custom
# global and local channels.
# if you want to apply default changes instead of doing it one by one.
# More info in our Discord Server!
default-channel:
  enabled: true
  # prefix: ''
  # suffix: ''
  color:
    normal: false
    special: false
    rgb: false
  radius: 0
  cooldown:
    time: 5
    message: '<P> &cYou can not send another message in {time} seconds.'
  format: ' &7{player} &8: &7{message}'