# If enabled, it will allow players to send blank messages using
# spaces ' '. Recommended leaving this 'false'.
allow-empty:
  enabled: false
  message: '<P> &cYou can not send an empty message.'
# If enabled, it will send a unique specific format to the console,
# just to be it more simple. This option applies to ALL formats.
simple-logger:
  enabled: false
  # You can use PlaceholderAPI, {PREFIX} and {SUFFIX}
  format: ' &7{player}: {message}'
# If disabled, it won't use the default format (from AsyncPlayerChatEvent).
# This will also allow chat compatibility with these features:
# - InteractiveChat support
# - Ignore chat command
# - Per Radius channel
# - Hover and Click events
# Enabling this is NOT recommended.
default-format: false