# This option handles if you want to disable the default join-quit messages.
# WARNING: This option DOES NOT disable the custom join-quit SIR messages,
#          only manages the default messages if those should appear or not.
default-messages:
  # Disables the default join message. Enabled by default
  disable-join: true
  # Disables the default quit message. Enabled by default
  disable-quit: true

# Manages the cooldown between join-quit messages to not show those
# messages if the players joins/leaves the server really quick.
cooldown:
  # Cooldown between join messages.
  join: 0
  # Cooldown between join and quit message.
  between: 0 # Not enabled by default
  # Cooldown between quit messages.
  quit: 0

# If a login plugin is installed, this section will be activated.
# Compatible login plugins: [ AuthMe, UserLogin ]
login:
  # it will send the messages after the player logs-in/register.
  # Disabling this, messages will send like no compatible login
  # plugin is installed in the server.
  enabled: true
  # This will send messages after some in-game ticks.
  # You can set this to 0 if you don't want this option or deleting
  # this path completely.
  ticks-after: 10
  # Enabling this will teleport the player before log-in/register if
  # a message group has a "spawn:" section.
  # Disabling it will teleport AFTER the player log-in/register.
  spawn-before: true

# If a vanish plugin is installed, this section will be activated.
# Compatible vanish plugins: [ CMI, EssentialsX, SuperVanish, etc ]
vanish:
  # This option send a join/quit section when a player changes its
  # vanish status. Disabling this won't send any messages when a player
  # changes its vanish status.
  enabled: true
  # If a message has a "spawn:" section, and this option is disabled,
  # that spawn section won't be executed.
  use-spawn: false
  # This option will allow vanished players to chat (or not) when enabled.
  # This feature is EXPERIMENTAL, so errors might occur using this feature
  # along with other chat-related modules.
  chat-key:
    enabled: false
    # The key to check in the chat message.
    key: ''
    # If the key is a regex one.
    regex: false
    # If not regex, will check if the key is a prefix or suffix.
    # Default: PREFIX
    place: PREFIX
    # The message to send when players are not allowed to chat.
    # Disable these messages setting it like this: []
    not-allowed: '<P> &cYou are not allowed to chat when you are vanished.'