# This option handles if you want to disable the default join-quit messages.
# WARNING: This option DOES NOT disable the custom join-quit SIR messages,
#          only manages the default messages if those should appear or not.
default-messages:
  # Disables the default join message. Enabled by default
  disable-join: true
  # Disables the default quit message. Enabled by default
  disable-quit: true

# Manages the cooldown between join-quit messages to not show those
# messages if the players joins/leaves the server really quick.
cooldown:
  # Cooldown between join messages.
  join: 0
  # Cooldown between join and quit message.
  between: 0 # Not enabled by default
  # Cooldown between quit messages.
  quit: 0